export const NOTIFICATION_MESSAGE_KEYS = [
	'MESSAGE_TAGGED_IN_POST',
	'MESSAGE_TAGGED_IN_COMMENT',
	'MESSAGE_LIKE_POST',
	'MESSAGE_LIKE_COMMENT',
	'MESSAGE_COMMENT_ON_POST',
	'MESSAGE_REPLY_ON_COMMENT',
	'MESSAGE_FRIEND_REQUEST',
	'MESSAGE_FRIEND_ACCEPTED',
	'MESSAGE_EVENT_INVITATION',
	'MESSAGE_EVENT_UPDATE',
	'MESSAGE_MENTION_IN_POST',
	'MESSAGE_MENTION_IN_COMMENT',
] as const;

export type NotificationMessageKey = (typeof NOTIFICATION_MESSAGE_KEYS)[number];
