// Seed data for User model
export const userSeeds = [
	{
		email: 'alice@example.com',
		password: 'hashed_password_1',
		refToken: 'refToken1',
		firstName: 'Alice',
		lastName: 'Smith',
		avatar: 'https://example.com/avatar.jpg',
		coverImage: null,
		bio: null,
		dateOfBirth: new Date('1990-01-01'),
		phone: '1234567890',
		location: { city: 'Hanoi', district: 'Hoan Kiem', address: '123 Main St' },
		favoritesSports: [],
		skillLevels: {},
		friends: [],
		following: [],
		followers: [],
		joinedGroups: [],
		isActive: true,
		isVerified: false,
		roles: ['user'],
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		email: 'bob@example.com',
		password: 'hashed_password_2',
		refToken: 'refToken2',
		firstName: 'Bob',
		lastName: 'Johnson',
		avatar: 'https://example.com/avatar2.jpg',
		coverImage: null,
		bio: null,
		dateOfBirth: new Date('1985-05-15'),
		phone: '9876543210',
		location: { city: 'HCM', district: '1', address: '456 Main St' },
		favoritesSports: [],
		skillLevels: {},
		friends: [],
		following: [],
		followers: [],
		joinedGroups: [],
		isActive: true,
		isVerified: false,
		roles: ['user'],
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];

// Seed data for Group model
export const groupSeeds = [
	{
		name: 'Developers',
		description: 'Group for developers',
		avatar: null,
		coverImage: null,
		admins: [],
		members: [],
		waitingList: [],
		sport: 'football',
		location: { city: 'Hanoi', district: 'Hoan Kiem' },
		isPrivate: false,
		memberCount: 0,
		requirePostApproval: false,
		autoApproveAdminPosts: true,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		name: 'Designers',
		description: 'Group for designers',
		avatar: null,
		coverImage: null,
		admins: [],
		members: [],
		waitingList: [],
		sport: 'basketball',
		location: { city: 'HCM', district: '1' },
		isPrivate: false,
		memberCount: 0,
		requirePostApproval: false,
		autoApproveAdminPosts: true,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];

// Seed data for FriendRequest model
export const friendRequestSeeds = [
	{
		sender: 'user1',
		recipient: 'user2',
		status: 'pending',
		message: null,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		sender: 'user2',
		recipient: 'user3',
		status: 'accepted',
		message: null,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];

// Seed data for Comment model
export const commentSeeds = [
	{
		postId: 'post1',
		author: 'user1',
		content: 'Great post!',
		parentId: null,
		likes: [],
		isActive: true,
		likeCount: 0,
		replyCount: 0,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		postId: 'post2',
		author: 'user2',
		content: 'Thanks for sharing!',
		parentId: null,
		likes: [],
		isActive: true,
		likeCount: 0,
		replyCount: 0,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];

// Seed data for Achievement model
export const achievementSeeds = [
	{
		name: 'First Login',
		description: 'Login for the first time',
		icon: 'https://example.com/icon1.png',
		criteria: '{}',
		isActive: true,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		name: 'Profile Complete',
		description: 'Completed profile information',
		icon: 'https://example.com/icon2.png',
		criteria: '{}',
		isActive: true,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];

// Seed data for UserAchievement model
export const userAchievementSeeds = [
	{
		userId: 'user1',
		achievementId: 'ach1',
		unlockedAt: new Date(),
		progress: 0,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		userId: 'user2',
		achievementId: 'ach2',
		unlockedAt: new Date(),
		progress: 0,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];

// Seed data for Post model
export const postSeeds = [
	{
		author: 'user1',
		content: 'Hello world!',
		type: 'text',
		images: [],
		video: null,
		eventId: null,
		groupId: null,
		likes: [],
		hashtags: [],
		taggedUsers: [],
		sharedFrom: null,
		likeCount: 0,
		commentCount: 0,
		shareCount: 0,
		sport: 'football',
		approvalStatus: 'approved',
		approvedBy: null,
		approvedAt: null,
		rejectionReason: null,
		rejectedBy: null,
		rejectedAt: null,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		author: 'user2',
		content: 'My first post!',
		type: 'text',
		images: [],
		video: null,
		eventId: null,
		groupId: null,
		likes: [],
		hashtags: [],
		taggedUsers: [],
		sharedFrom: null,
		likeCount: 0,
		commentCount: 0,
		shareCount: 0,
		sport: 'basketball',
		approvalStatus: 'approved',
		approvedBy: null,
		approvedAt: null,
		rejectionReason: null,
		rejectedBy: null,
		rejectedAt: null,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];

// Seed data for Event model
export const eventSeeds = [
	{
		title: 'Hackathon',
		description: 'A fun hackathon event',
		image: null,
		organizer: 'user1',
		sport: 'football',
		startDate: new Date('2024-07-01'),
		endDate: new Date('2024-07-02'),
		location: {
			name: 'Hanoi Stadium',
			address: '1 Le Duan',
			city: 'Hanoi',
			district: 'Hoan Kiem',
		},
		minParticipants: 1,
		maxParticipants: 100,
		participants: [],
		status: 'upcoming',
		participantCount: 0,
	},
	{
		title: 'Workshop',
		description: 'A design workshop',
		image: null,
		organizer: 'user2',
		sport: 'basketball',
		startDate: new Date('2024-08-01'),
		endDate: new Date('2024-08-02'),
		location: {
			name: 'HCM Arena',
			address: '2 Nguyen Hue',
			city: 'HCM',
			district: '1',
		},
		minParticipants: 1,
		maxParticipants: 50,
		participants: [],
		status: 'upcoming',
		participantCount: 0,
	},
];

// Seed data for Notification model
export const notificationSeeds = [
	{
		recipient: 'user1',
		sender: 'user2',
		type: 'friend_request',
		title: 'Welcome!',
		message: 'Welcome to the platform!',
		referenceId: null,
		referenceModel: null,
		isRead: false,
		isActive: true,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		recipient: 'user2',
		sender: 'user1',
		type: 'friend_request',
		title: 'Friend Request',
		message: 'You have a new friend request.',
		referenceId: null,
		referenceModel: null,
		isRead: false,
		isActive: true,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];
