export enum NotificationType {
	FRIEND_REQUEST = 'friend_request',
	FRIEND_REQUEST_ACCEPTED = 'friend_request_accepted',
	FRIEND_REQUEST_DECLINED = 'friend_request_declined',
	EVENT_INVITATION = 'event_invitation',
	GROUP_INVITATION = 'group_invitation',
	GROUP_INVITATION_ACCEPTED = 'group_invitation_accepted',
	GROUP_INVITATION_REJECTED = 'group_invitation_rejected',
	GROUP_JOIN_REQUEST = 'group_join_request',
	LIKE = 'like',
	COMMENT = 'comment',
	POST_APPROVED = 'post_approved',
	POST_REJECTED = 'post_rejected',
	ACHIEVEMENT_UNLOCKED = 'achievement_unlocked',
	MENTION = 'mention',
	FOLLOW = 'follow',
	SHARE = 'share',
	REQUEST_APPROVE_POST = 'request_approve_post',
	EVENT_INVITATION_ACCEPTED = 'event_invitation_accepted',
	EVENT_INVITATION_REJECTED = 'event_invitation_rejected',
}

export enum ReferenceModel {
	POST = 'Post',
	EVENT = 'Event',
	GROUP = 'Group',
	COMMENT = 'Comment',
	USER = 'User',
	ACHIEVEMENT = 'Achievement',
	FRIEND_REQUEST = 'FriendRequest',
}
